# Generated by Django 2.2.4 on 2019-08-19 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Note',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Type',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('ordinal', models.IntegerField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='swimdiary.Note')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='swimdiary.Type')),
            ],
            options={
                'db_table': 'Week',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('length', models.FloatField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='swimdiary.Note')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='swimdiary.Type')),
            ],
            options={
                'db_table': 'Training',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('fins', models.BooleanField()),
                ('paddles', models.BooleanField()),
                ('snorkel', models.BooleanField()),
                ('plane', models.BooleanField()),
                ('board', models.BooleanField()),
                ('rubber', models.BooleanField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='swimdiary.Note')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='swimdiary.Type')),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
