# Generated by Django 2.2.4 on 2019-08-20 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimdiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='training',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='swimdiary.Training'),
        ),
        migrations.AddField(
            model_name='training',
            name='week',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='swimdiary.Week'),
        ),
    ]
