# Generated by Django 2.2.4 on 2019-08-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimdiary', '0003_auto_20190820_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('year', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Season',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='swimdiary.Note'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='swimdiary.Type'),
        ),
        migrations.AlterField(
            model_name='training',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='swimdiary.Note'),
        ),
        migrations.AlterField(
            model_name='training',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='swimdiary.Type'),
        ),
        migrations.AlterField(
            model_name='week',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='swimdiary.Note'),
        ),
        migrations.AlterField(
            model_name='week',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='swimdiary.Type'),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='swimdiary.Note')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='swimdiary.Season')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='swimdiary.Type')),
            ],
            options={
                'db_table': 'Period',
            },
        ),
        migrations.AddField(
            model_name='week',
            name='period',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='swimdiary.Period'),
        ),
    ]
