# Generated by Django 2.2.4 on 2019-08-26 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimdiary', '0004_auto_20190826_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimdiary.Period'),
        ),
    ]
